### ISSUE TITLE
Are the file:// and chrome:// protocol supported?

### ISSUE THREAD

**Issue by vsemozhetbyt** [JasonBarnabe/stylish#219]
In the Chrome I try to write a global style for links color. However it does not work for local pages and special pages with file:// and chrome:// protocols. Additional sections with  chrome://* and file://* patters have no effect too.

**Comment by JasonBarnabe** [comment]
Chrome restricts what protocols extensions can access. I do see that [the docs](https://developer.chrome.com/extensions/match_patterns) mention `file` if the user opts in, so I can look into that. But for `chrome` I think you're out of luck.

**Comment by JasonBarnabe** [comment]
Filed https://github.com/JasonBarnabe/stylish-chrome/issues/25

**Comment by vsemozhetbyt** [comment]
Thank you.

**Comment by datdinhquoc** [comment]
> Chrome restricts what protocols extensions can access. I do see that [the docs](https://developer.chrome.com/extensions/match_patterns) mention `file` if the user opts in, so I can look into that. But for `chrome` I think you're out of luck.

this is sad :(
