### ISSUE TITLE
Exclude sites by domains or prefixes instead of regexp

### ISSUE THREAD

**Issue by polyzen** [JasonBarnabe/stylish#220]
sudokode> polyzen: I can't wait til stylish allows you to block domains or prefixes instead of having to use that ugly regexp
sudokode> domain("!google.com")
sudokode> url-prefix("!about")
sudokode> and then multiple domains is just a pipe and the next one

@sudokode

**Comment by JasonBarnabe** [comment]
Stylish can only supports what Firefox supports. You'd have to ask Mozilla, but I doubt they'd do it. Learn to love the regexps!

**Comment by polyzen** [comment]
Thank you for the swift response
