### ISSUE TITLE
Exclude sites with existing @-moz-document rule types

### ISSUE THREAD

**Issue by sudokode** [JasonBarnabe/stylish#221]
Currently the only way to exclude certain URLs is through a regexp rule type:
`@-moz-document url-prefix('http://'), url-prefix('https://'), regexp('^https?://(?!foo\\.com).*') { ... }`

And multiple domains/URLs quickly fill up the screen.  This could be solved by checking the first character of the other rule types.  If it's an exclamation point ('!'), treat it as a negation of that type:
`@-moz-document url-prefix('http://'), url-prefix('https://'), domain('!foo.com'), url('!http://bar.com/foo') { ... }`

**Comment by sudokode** [comment]
Obviously #220 beat me to it.

**Comment by xenithorb** [comment]
The original way to exclude doesn't seem to work anymore, can someone confirm?
