### ISSUE TITLE
Broke in Komodo 9

### ISSUE THREAD

**Issue by mjbrancato** [JasonBarnabe/stylish#233]
This does not work in Komodo 9. It says it's incompatible.

**Comment by Defman21** [comment]
Just build Stylish for yourself. @JasonBarnabe please, update the release, the xpi must contain this commit to get the add-on works in Komodo 9: https://github.com/JasonBarnabe/stylish/commit/381d6d3cf2eae98a14cba81901cc91ca19f4ee64
