### ISSUE TITLE
Toggle Auto-Indent in Editor

### ISSUE THREAD

**Issue by Gitoffthelawn** [JasonBarnabe/stylish#235]
Is there any way to turn off the auto-indent feature in the style editor?

If not, could that be added as a preference?

**Comment by LouCypher** [comment]
#180

On Wednesday, August 12, 2015, Gitoffthelawn <notifications@github.com>
wrote:

> Is there any way to turn off the auto-indent feature in the style editor?
>
> If not, could that be added as a preference?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JasonBarnabe/stylish/issues/235>.
>


--

**Comment by Gitoffthelawn** [comment]
Thank you Lou!
