### ISSUE TITLE
Copy (or Cut) and paste in style editor fails

### ISSUE THREAD

**Issue by Gitoffthelawn** [JasonBarnabe/stylish#236]
When copying (or cutting) large sections of a style using the integrated editor, all that is copied to the clipboard is a dash (-).  This makes it impossible to easily manipulate lengthy styles.

I wonder if this is a Firefox bug, as I think Stylish may just be using the native developer editor.

Tested on: Stylish 2.0.2.1, Firefox 40.0.2, Win 7 SP1

**Comment by JasonBarnabe** [comment]
Yes, Stylish uses what comes with Firefox, so if it doesn't work, it's a Firefox thing.
