### ISSUE TITLE
Orion Editor stopped working in latest Firefox Nightly

### ISSUE THREAD

**Issue by Halibut80** [JasonBarnabe/stylish#243]
Win 8.1 x64, Firefox Nightly 44.0a1 x64 BuildID:20150924030231, Stylish 2.0.2.1, e10s disabled.

**Comment by JasonBarnabe** [comment]
Stylish (or Firefox) haven't used Orion in a while; it's CodeMirror now. Did you really mean Orion?

**Comment by Halibut80** [comment]
Uh, sorry. Yes, I mean CodeMirror.

**Comment by nt1m** [comment]
@JasonBarnabe Any chance you could upload a new version on AMO with this fix please ? Thanks !
