### ISSUE TITLE
Create pt-PT locale

### ISSUE THREAD

**Issue by SW1FT** [JasonBarnabe/stylish#263]
I'd like to ask if you could create the pt-PT locale translation files and add them to Transifex. I'll provide the full translation based on the Firefox pt-PT locale glossary.

**Comment by JasonBarnabe** [comment]
You should be able to request languages from Transifex, but I've added pt-PT anyway. Thanks.

**Comment by SW1FT** [comment]
Thank you. I've just finished translating it, you can merge it.
