### ISSUE TITLE
Useless after Nightly updated to 46.0a1 20160107

### ISSUE THREAD

**Issue by lychichem** [JasonBarnabe/stylish#264]
![default](https://cloud.githubusercontent.com/assets/9316590/12190780/a385528a-b607-11e5-904a-15ea1b3158f4.PNG)
Browser console shows this.

**Comment by yfdyh000** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1237605

**Comment by lychichem** [comment]
A way to fix:
http://bbs.kafan.cn/forum.php?mod=viewthread&tid=1875381&page=1#pid36717762

**Comment by yfdyh000** [comment]
#265 fixed it.
